import {spawn} from 'node:child_process';
import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {stripVTControlCharacters} from 'node:util';
const server=spawn(process.execPath,[fileURLToPath(new URL('../../node_modules/vite/bin/vite.js',import.meta.url)),'preview','--host','127.0.0.1','--port','4176','--strictPort'],{cwd:new URL('../../',import.meta.url),stdio:['ignore','pipe','inherit']});
let browser;
try{
 await new Promise((resolve,reject)=>{let out='';const t=setTimeout(()=>reject(new Error('Forest preview timeout')),10000);server.stdout.on('data',d=>{out+=d;if(stripVTControlCharacters(out).includes('Local:')){clearTimeout(t);resolve();}});server.on('error',reject);});
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));await page.route(/mc\.yandex/,r=>r.abort());
 await page.goto('http://127.0.0.1:4176/');
 const save=JSON.parse(await fs.readFile(new URL('../fixtures/terrain-display-map.json',import.meta.url),'utf8'));
 const hexes=[];for(let q=-2;q<=2;q++)for(let r=-2;r<=2;r++)if(Math.max(Math.abs(q),Math.abs(r),Math.abs(q+r))<=2)hexes.push({q,r});
 save.map.kingdoms=[];save.map.obstacles=[];save.map.rivers=[];save.map.roads=[];save.map.crossings=[];save.map.waterPoiByHexKey={};save.map.terrainByHexKey={};
 save.map.regions=[{...save.map.regions[0],id:1,hexes,centerHex:{q:0,r:0},anchorHex:{q:0,r:0},biomeId:'plain_deciduous_forest',generationMode:'classic',kingdomId:undefined,suppressCentralPoi:false,centralPoiKind:'capital',pointsOfInterest:[],pointOfInterestKinds:{}}];
 save.map.candidateHexes=[];save.map.biomeOverrideByHexKey={'0,0':'deciduous_woodland','2,-1':'dead_woodland','-2,1':'coniferous_woodland','1,0':'plain_mixed_forest','-1,0':'plain_coniferous_forest','2,0':'swamp_forest'};
 save.ui={...save.ui,generationMode:'classic',isMapRotated:false,selectedHex:null,mapScale:2};
 const load=async()=>{await page.locator('input[type=file]').setInputFiles({name:'forest.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(save))});await page.waitForTimeout(150);};
 await load();const toggle=page.locator('.biome-display-toggle');
 assert.equal(await page.locator('.forest-canopy-layer').count(),0);
 await toggle.click();assert.equal(await page.locator('.forest-canopy-layer').count(),0);
 await toggle.click();
 assert.equal(await toggle.getAttribute('data-mode'),'color');
 assert.equal(await page.locator('image.terrain-overlay').count(),1,'Swamp forest keeps the swamp ground overlay');
 assert.equal(await page.locator('[data-woodland-key="2,0"]').getAttribute('data-woodland-mode'),'islands');
 assert.equal(await page.locator('[data-tree-marks="edge"]').count(),1);
 assert.equal(await page.locator('[data-tree-marks="inside"]').count(),1);
 assert.equal(await page.locator('.forest-canopy-layer').count(),1);
 assert.equal(await page.locator('#forest-union-outline').count(),1);
 assert.equal(await page.locator('.forest-canopy-layer [stroke="#242A16"]').count(),0,'Individual outlines must not leave internal seams');
 assert.equal(await page.locator('[data-woodland-key="0,0"]').getAttribute('data-woodland-mode'),'clearings');
 assert.equal(await page.locator('[data-woodland-key="2,-1"]').getAttribute('data-woodland-mode'),'islands');
 for(const patch of await page.locator('[data-woodland-key]').all())assert.ok([3,4].includes(await patch.locator('path').count()));
 const signatures=()=>page.locator('[data-woodland-key]').evaluateAll(ns=>Object.fromEntries(ns.map(n=>[n.dataset.woodlandKey,{composition:n.dataset.composition,rotation:n.dataset.rotation,paths:[...n.querySelectorAll('path')].map(p=>p.getAttribute('d'))}])));
 const canopyBeforeLake=await page.locator('[data-forest-shape="dense"]').getAttribute('d');
 save.map.terrainByHexKey={'-1,0':{terrainOverride:'lake',lakeId:900}};await load();
 await page.locator('.lake-water-layer [data-lake-shape]').waitFor({state:'attached'});
 assert.equal(await page.locator('[data-forest-shape="dense"]').getAttribute('d'),canopyBeforeLake,'Lake overlays rather than replacing canopy');
 assert.equal(await page.locator('.lake-water-layer [data-lake-shape]').count(),1);
 assert.ok(await page.locator('[fill="#91B575"]').count()>0,'Original forest ground restored');
 const before=await signatures();await toggle.click();await toggle.click();await toggle.click();assert.deepEqual(await signatures(),before);
 await page.locator('.rotate-map-button').click();assert.deepEqual(await signatures(),before);
 assert.ok(await page.locator('.top-hex-grid').evaluate(n=>n===n.parentElement.lastElementChild));
 await page.locator('.rotate-map-button').click();
 const menu=page.locator('details.export-menu');if(await menu.getAttribute('open')===null)await menu.locator('summary').click();
 const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'PNG',exact:true}).click()]);
 const bytes=await fs.readFile(await download.path());assert.ok(bytes.length>10000);
 await fs.mkdir(new URL('../../reports/',import.meta.url),{recursive:true});await fs.writeFile(new URL('../../reports/terrain-v2-forest.png',import.meta.url),bytes);
 save.map.regions[0].hexes.push({q:3,r:0});save.map.biomeOverrideByHexKey['3,0']='deciduous_woodland';await load();
 await page.locator('[data-woodland-key="3,0"]').waitFor({state:'attached'});
 const grown=await signatures();for(const [k,v]of Object.entries(before))assert.deepEqual(grown[k],v);
 save.map.regions[0].biomeId='deciduous_woodland';save.map.regions[0].woodlandStyle='clearings';save.map.biomeOverrideByHexKey={};await load();
 await page.waitForFunction(()=>document.querySelectorAll('[data-woodland-mode="islands"]').length===0 && document.querySelectorAll('[data-woodland-mode="clearings"]').length===18);
 assert.equal(await page.locator('[data-woodland-mode="islands"]').count(),0);
 assert.equal(await page.locator('[data-woodland-mode="clearings"]').count(),hexes.length-1);
 assert.equal(await page.locator('[data-woodland-key="-1,0"]').count(),0,'No woodland contours on lake hexes');
 assert.deepEqual(errors,[]);console.log('Forest display: Color only, 3/4 islands and clearings, stable growth, rotation, top grid and real PNG export passed.');
}finally{if(browser)await browser.close();server.kill();}
